const portfolioContent = {
  en: {
    career: [
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",location:"Mendoza, Argentina",roles:[{role:"Senior Cloud Engineer",period:"May 2026 — Present"},{role:"Cloud Engineer",period:"Jun 2025 — May 2026"}],summary:"My current stage, focused on cloud migrations and infrastructure delivery in AWS environments.",technical:["GitHub-based CI/CD pipelines","AWS MGN migrations","EC2, Auto Scaling and Load Balancers","AWS Control Tower and Organizations","Windows Server, IIS and SQL Server workloads on EC2","Grafana monitoring and alerting"],professional:["Working inside large migration programs with clearly defined responsibilities","Adapting deployment pipelines to target architectures","Balancing migration execution, infrastructure and operations","Continued growth into a Senior Cloud Engineer role"]},
      {company:"Netrix Global",logo:"https://www.netrixglobal.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=netrixglobal.com&sz=128",initials:"N",location:"Argentina",roles:[{role:"Sr. Cloud Engineer",period:"Sep 2022 — Jun 2025"}],summary:"A major cloud engineering stage, including AWS migrations, landing-zone services, CI/CD and infrastructure for data-oriented workloads.",technical:["AWS Control Tower, Organizations and IAM Identity Center","Lambda, DynamoDB, API Gateway and Load Balancers","EC2 workloads used by Power BI consumers","AWS MGN migration of ~80 Red Hat Linux servers","Alternative image → S3 → AMI migration path for unsupported workloads","CI/CD and some Kubernetes exposure"],professional:["Owning the infrastructure scope while collaborating with specialized data teams","Designing fallback approaches when the preferred migration tool was not supported","Working with external connectivity requirements and multiple integrations","Handling large batches of server migrations"]},
      {company:"3XM Group",logo:"https://www.3xmgroup.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=3xmgroup.com&sz=128",initials:"3X",location:"Argentina",roles:[{role:"DevOps",period:"Jan 2022 — Sep 2022"}],summary:"A full DevOps and AWS role maintaining infrastructure for different customers and application architectures.",technical:["EC2 and ECS","Lambda","Elastic Load Balancing","CloudFront","Elastic Beanstalk","AWS infrastructure operations"],professional:["Working across multiple customers instead of one fixed platform","Adapting quickly to different architectures and operational needs","Strengthening the transition from enterprise infrastructure into cloud-native operations"]},
      {company:"Accenture",logo:"https://www.accenture.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=accenture.com&sz=128",initials:"A",location:"Argentina",roles:[{role:"Tech Arch Delivery Sr Analyst",period:"Nov 2020 — Dec 2021"}],summary:"My first strong AWS stage, combining application support, cloud services, CI/CD, monitoring and team coordination.",technical:["AWS: S3, ElastiCache, CloudFront, Route 53, Lambda and Secrets Manager","Azure DevOps CI/CD","Migration of deployment pipelines from Octopus to Azure DevOps","Datadog monitoring","ServiceNow","Windows Server administration"],professional:["Coordinating a distributed team of three people across China and India","Planning and executing application deployments","Working across time zones and remote teams","Starting the transition from traditional infrastructure toward AWS"]},
      {company:"EY",logo:"https://www.ey.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=ey.com&sz=128",initials:"EY",location:"Argentina",roles:[{role:"SharePoint Infrastructure Systems Management & Support",period:"Dec 2018 — Mar 2020"}],summary:"Enterprise support with a stronger infrastructure focus around SharePoint on-premises environments.",technical:["SharePoint infrastructure management and support","SharePoint patching","Windows Server 2012 / 2016","Splunk monitoring and log troubleshooting","ServiceNow","SharePoint Designer and InfoPath"],professional:["Operating enterprise environments with formal support processes","Improving troubleshooting through logs and monitoring","Developing stronger operational discipline"]},
      {company:"Softtek",logo:"https://www.softtek.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=softtek.com&sz=128",initials:"S",location:"Buenos Aires, Argentina",roles:[{role:"SharePoint Infrastructure / Developer",period:"Sep 2016 — Dec 2018"}],summary:"A mixed infrastructure and frontend-development role centered around Microsoft SharePoint.",technical:["SharePoint 2010 / 2013 / 2016 infrastructure","HTML, CSS, JavaScript and AngularJS","Bootstrap and jQuery","SQL Server 2012 / 2016","Windows Server 2012 / 2016","Azure tenant administration"],professional:["Understanding applications from both infrastructure and frontend perspectives","Working across multiple technical layers instead of a single specialty","Building deeper enterprise-platform experience"]},
      {company:"Solnik S.A.",logo:"https://www.solnik.com.ar/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=solnik.com.ar&sz=128",initials:"S",location:"Argentina",roles:[{role:"Technical Support / Server Administration",period:"Jun 2015 — Aug 2016"}],summary:"A hybrid role between first-level support and Windows server administration.",technical:["Active Directory administration","Office 365 migration work","SharePoint","Windows Server 2008 R2 / 2012","Structured cabling","IP telephony"],professional:["Moving from end-user support into server administration","Participating in organization-wide migration work","Taking more responsibility for core IT services"]},
      {company:"Readymind IT",logo:"https://readymind.ms/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=readymind.ms&sz=128",initials:"R",location:"Buenos Aires, Argentina",roles:[{role:"Technical Support",period:"Oct 2013 — Feb 2015"}],summary:"My professional starting point: end-user support, physical infrastructure and Windows Server deployments for different customer environments.",technical:["Physical on-premises server configuration","Active Directory, DHCP and DNS","Exchange and IIS","File and print services","Windows Server 2008 / 2012","IP telephony","L1 hardware and software support"],professional:["Learning to troubleshoot from the user all the way to the server","Working directly with customers and different business environments","Building a hands-on infrastructure foundation","Learning responsibility through day-to-day operational support"]}
    ],
    cases: [
      {featured:true,company:"Netrix Global",logo:"https://www.netrixglobal.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=netrixglobal.com&sz=128",initials:"N",category:"AWS Migration & Architecture",title:"On-Prem Data Platform Migration to AWS",challenge:"Migrate an on-premises data-oriented application to AWS while preserving numerous external integrations, including banking connections and other third-party dependencies.",architecture:"The AWS environment included Lambda, DynamoDB, API Gateway, Load Balancers and EC2 workloads used by Power BI consumers. The landing-zone foundation also required AWS Control Tower, Organizations and IAM Identity Center.",contribution:"I was responsible for the AWS infrastructure scope and platform setup. The data-engineering work itself was handled by another team.",outcome:"An AWS foundation capable of supporting the migrated application, its external connectivity and the infrastructure required by analytics consumers.",services:["Control Tower","Organizations","IAM Identity Center","Lambda","DynamoDB","API Gateway","Load Balancers","EC2","Power BI"],diagram:["On-Prem App","API / Integrations","AWS Services","Data Platform","EC2 / Power BI"]},
      {company:"Netrix Global",logo:"https://www.netrixglobal.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=netrixglobal.com&sz=128",initials:"N",category:"Large-Scale Server Migration",title:"Migration of ~80 Red Hat Linux Servers to EC2",challenge:"Move around 80 Red Hat Linux servers running multiple OS versions from VMware on-premises to AWS.",architecture:"The primary path used AWS MGN to replicate supported servers directly into EC2. For operating-system versions not supported by MGN, an alternative image-based migration workflow was required.",contribution:"I participated in the infrastructure and migration work, including the fallback path: create an image from the on-prem VMware workload, upload it to S3, create an AMI and launch the resulting EC2 instance.",outcome:"A mixed migration strategy that allowed both MGN-supported and unsupported Red Hat workloads to be moved into EC2.",services:["AWS MGN","EC2","S3","AMI","VMware","Red Hat Linux"],diagram:["VMware","MGN","EC2","Fallback: Image → S3","AMI → EC2"]},
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",category:"CI/CD & Migration",title:"Transportation Payment Platform Migration",challenge:"Support a large migration program for a transportation payment application in the United States.",architecture:"My scope was mainly the delivery pipeline layer rather than the AWS platform itself.",contribution:"I reorganized and adapted GitHub-based pipelines so the application delivery process aligned with the target migration environment.",outcome:"Deployment workflows better aligned with the migration target and delivery process.",services:["GitHub","GitHub Actions","CI/CD","Migration"],diagram:["Source","GitHub","Pipelines","Target Platform"]},
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",category:"AWS Migration",title:"MGN Migration with Auto Scaling Architecture",challenge:"Migrate workloads to AWS while also preparing a scalable target architecture and account foundation.",architecture:"The target environment combined AWS MGN, EC2, Auto Scaling and Load Balancers, with AWS Control Tower and Organizations used for the broader AWS environment.",contribution:"I worked on the migration and infrastructure components as well as GitHub-based pipelines used in the delivery process.",outcome:"A migration path backed by a more scalable EC2 architecture and a structured AWS account foundation.",services:["AWS MGN","EC2","Auto Scaling","Load Balancers","Control Tower","Organizations","GitHub"],diagram:["On-Prem","AWS MGN","EC2 Auto Scaling","Load Balancer","Application"]},
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",category:"Windows & SQL Migration",title:"Windows IIS and SQL Server Migration to AWS",challenge:"Migrate Windows application servers running IIS and SQL Server workloads into AWS.",architecture:"The current target is based on EC2-hosted Windows application servers running IIS and EC2-hosted SQL Server, with Grafana used for monitoring and alerts.",contribution:"I am working on the AWS infrastructure, Windows/IIS and SQL migration context, Grafana monitoring and GitHub pipelines.",outcome:"An EC2-based target architecture for the application and database workloads with operational visibility through monitoring and alerting.",services:["EC2","Windows Server","IIS","SQL Server","Grafana","GitHub","CI/CD"],diagram:["Users","Load Balancer","EC2 / IIS","EC2 / SQL Server","Grafana"]}
    ],
    certifications:[
      {category:"AWS",name:"Well-Architected Proficient",badge:"AWS",logo:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=thumbnail",logoFallback:"https://aws.amazon.com/favicon.ico"},
      {category:"AWS",name:"AWS API Security",badge:"AWS",logo:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=thumbnail",logoFallback:"https://aws.amazon.com/favicon.ico"},
      {category:"AI",name:"Claude Certified Associate — Foundations",badge:"AI",logo:"https://claude.ai/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=claude.ai&sz=128"},
      {category:"Agile",name:"Scrum Foundation Professional Certificate (SFPC) — Spanish",badge:"S",logo:"https://certiprof.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=certiprof.com&sz=128"},
      {category:"AWS",name:"AWS Partner: Cloud Economics Accreditation",badge:"AWS",logo:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=thumbnail",logoFallback:"https://aws.amazon.com/favicon.ico"}
    ],
    education:[
      {institution:"Instituto Superior Tecnologico Empresarial Argentino (ISTEA)",program:"Higher Education — Information Technology",period:"2020 — 2024"},
      {institution:"Ingeniero Eduardo Latzina",program:"High School — Computer Technician",period:"2006 — 2013"}
    ],
    skills:[
      {title:"AWS Infrastructure & Architecture",level:"Primary focus",items:["AWS","EC2","ECS","Lambda","S3","IAM","Route 53","API Gateway","Load Balancers","Control Tower","Organizations","IAM Identity Center"]},
      {title:"Cloud Migrations",level:"Primary focus",items:["AWS MGN","VMware to AWS","Windows Workloads","Linux / Red Hat","AMI Import","Cutover Planning"]},
      {title:"Infrastructure as Code & Delivery",level:"Primary focus",items:["Terraform","Terragrunt","AWS CDK","GitHub Actions","Azure DevOps","CI/CD","Git"]},
      {title:"Operations & Observability",level:"Primary focus",items:["Grafana","Datadog","Splunk","ServiceNow","Python","Boto3","Linux"]},
      {title:"Containers",level:"Complementary",items:["Docker","ECS","ECR","Kubernetes","Helm","EKS"]},
      {title:"Infrastructure Foundation",level:"Background",items:["Windows Server","Active Directory","DNS","DHCP","IIS","Exchange","SharePoint","SQL Server","Office 365"]}
    ]
  },

  es: {
    career: [
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",location:"Mendoza, Argentina",roles:[{role:"Senior Cloud Engineer",period:"May 2026 — Actualidad"},{role:"Cloud Engineer",period:"Jun 2025 — May 2026"}],summary:"Mi etapa actual, enfocada en migraciones cloud y entrega de infraestructura en entornos AWS.",technical:["Pipelines CI/CD basados en GitHub","Migraciones con AWS MGN","EC2, Auto Scaling y Load Balancers","AWS Control Tower y Organizations","Workloads Windows Server, IIS y SQL Server sobre EC2","Monitoreo y alarmas con Grafana"],professional:["Trabajar dentro de programas de migración grandes con responsabilidades bien definidas","Adaptar pipelines de deployment a arquitecturas objetivo","Combinar ejecución de migraciones, infraestructura y operación","Crecimiento hacia un rol de Senior Cloud Engineer"]},
      {company:"Netrix Global",logo:"https://www.netrixglobal.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=netrixglobal.com&sz=128",initials:"N",location:"Argentina",roles:[{role:"Sr. Cloud Engineer",period:"Sep 2022 — Jun 2025"}],summary:"Una etapa muy importante de cloud engineering, con migraciones AWS, servicios de landing zone, CI/CD e infraestructura para workloads orientados a datos.",technical:["AWS Control Tower, Organizations e IAM Identity Center","Lambda, DynamoDB, API Gateway y Load Balancers","Workloads EC2 utilizados por consumidores de Power BI","Migración con AWS MGN de ~80 servidores Red Hat Linux","Ruta alternativa imagen → S3 → AMI para workloads no soportados","CI/CD y algo de exposición a Kubernetes"],professional:["Responsabilidad sobre el alcance de infraestructura colaborando con equipos especializados de datos","Diseñar alternativas cuando la herramienta de migración preferida no era compatible","Trabajar con requerimientos de conectividad externa y múltiples integraciones","Manejar migraciones de grandes lotes de servidores"]},
      {company:"3XM Group",logo:"https://www.3xmgroup.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=3xmgroup.com&sz=128",initials:"3X",location:"Argentina",roles:[{role:"DevOps",period:"Ene 2022 — Sep 2022"}],summary:"Un rol completamente DevOps y AWS, manteniendo infraestructura para distintos clientes y arquitecturas de aplicaciones.",technical:["EC2 y ECS","Lambda","Elastic Load Balancing","CloudFront","Elastic Beanstalk","Operación de infraestructura AWS"],professional:["Trabajar con múltiples clientes en lugar de una única plataforma","Adaptarme rápidamente a diferentes arquitecturas y necesidades operativas","Fortalecer la transición desde infraestructura enterprise hacia operaciones cloud"]},
      {company:"Accenture",logo:"https://www.accenture.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=accenture.com&sz=128",initials:"A",location:"Argentina",roles:[{role:"Tech Arch Delivery Sr Analyst",period:"Nov 2020 — Dic 2021"}],summary:"Mi primera etapa fuerte en AWS, combinando soporte de aplicaciones, servicios cloud, CI/CD, monitoreo y coordinación de equipo.",technical:["AWS: S3, ElastiCache, CloudFront, Route 53, Lambda y Secrets Manager","Azure DevOps CI/CD","Migración de pipelines de Octopus hacia Azure DevOps","Monitoreo con Datadog","ServiceNow","Administración Windows Server"],professional:["Coordinación de un equipo distribuido de tres personas entre China e India","Planificación y ejecución de deployments de aplicaciones","Trabajo entre zonas horarias y equipos remotos","Inicio de la transición desde infraestructura tradicional hacia AWS"]},
      {company:"EY",logo:"https://www.ey.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=ey.com&sz=128",initials:"EY",location:"Argentina",roles:[{role:"SharePoint Infrastructure Systems Management & Support",period:"Dic 2018 — Mar 2020"}],summary:"Soporte enterprise con mayor foco en infraestructura alrededor de entornos SharePoint on-premises.",technical:["Gestión y soporte de infraestructura SharePoint","Patching de SharePoint","Windows Server 2012 / 2016","Monitoreo y troubleshooting de logs con Splunk","ServiceNow","SharePoint Designer e InfoPath"],professional:["Operar ambientes enterprise con procesos formales de soporte","Mejorar troubleshooting mediante logs y monitoreo","Desarrollar mayor disciplina operativa"]},
      {company:"Softtek",logo:"https://www.softtek.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=softtek.com&sz=128",initials:"S",location:"Buenos Aires, Argentina",roles:[{role:"SharePoint Infrastructure / Developer",period:"Sep 2016 — Dic 2018"}],summary:"Un rol mixto de infraestructura y desarrollo frontend centrado en Microsoft SharePoint.",technical:["Infraestructura SharePoint 2010 / 2013 / 2016","HTML, CSS, JavaScript y AngularJS","Bootstrap y jQuery","SQL Server 2012 / 2016","Windows Server 2012 / 2016","Administración de tenant en Azure"],professional:["Entender aplicaciones tanto desde infraestructura como desde frontend","Trabajar sobre múltiples capas técnicas y no una sola especialidad","Construir experiencia más profunda en plataformas enterprise"]},
      {company:"Solnik S.A.",logo:"https://www.solnik.com.ar/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=solnik.com.ar&sz=128",initials:"S",location:"Argentina",roles:[{role:"Technical Support / Server Administration",period:"Jun 2015 — Ago 2016"}],summary:"Un rol híbrido entre soporte de primer nivel y administración de servidores Windows.",technical:["Administración de Active Directory","Trabajo de migración hacia Office 365","SharePoint","Windows Server 2008 R2 / 2012","Cableado estructurado","Telefonía IP"],professional:["Pasar del soporte a usuario hacia administración de servidores","Participar en migraciones con impacto a nivel organizacional","Tomar mayor responsabilidad sobre servicios centrales de IT"]},
      {company:"Readymind IT",logo:"https://readymind.ms/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=readymind.ms&sz=128",initials:"R",location:"Buenos Aires, Argentina",roles:[{role:"Technical Support",period:"Oct 2013 — Feb 2015"}],summary:"Mi punto de partida profesional: soporte a usuarios, infraestructura física y despliegues Windows Server para distintos clientes.",technical:["Configuración de servidores físicos on-premises","Active Directory, DHCP y DNS","Exchange e IIS","File Server y Print Server","Windows Server 2008 / 2012","Telefonía IP","Soporte L1 de hardware y software"],professional:["Aprender a diagnosticar desde el usuario hasta el servidor","Trabajar directamente con clientes y distintos tipos de negocio","Construir una base hands-on de infraestructura","Aprender responsabilidad mediante el soporte operativo diario"]}
    ],
    cases:[
      {featured:true,company:"Netrix Global",logo:"https://www.netrixglobal.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=netrixglobal.com&sz=128",initials:"N",category:"Migración & Arquitectura AWS",title:"Migración de Plataforma de Datos On-Prem a AWS",challenge:"Migrar una aplicación orientada a datos desde on-premises hacia AWS preservando numerosas integraciones externas, incluyendo conexiones bancarias y otras dependencias de terceros.",architecture:"El entorno AWS incluía Lambda, DynamoDB, API Gateway, Load Balancers y workloads EC2 utilizados por consumidores de Power BI. La base de landing zone también requería AWS Control Tower, Organizations e IAM Identity Center.",contribution:"Fui responsable del alcance de infraestructura AWS y de la configuración de plataforma. El trabajo de ingeniería de datos en sí fue realizado por otro equipo.",outcome:"Una base AWS capaz de soportar la aplicación migrada, su conectividad externa y la infraestructura requerida por los consumidores de analytics.",services:["Control Tower","Organizations","IAM Identity Center","Lambda","DynamoDB","API Gateway","Load Balancers","EC2","Power BI"],diagram:["App On-Prem","API / Integraciones","Servicios AWS","Plataforma de Datos","EC2 / Power BI"]},
      {company:"Netrix Global",logo:"https://www.netrixglobal.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=netrixglobal.com&sz=128",initials:"N",category:"Migración Masiva de Servidores",title:"Migración de ~80 Servidores Red Hat Linux a EC2",challenge:"Mover aproximadamente 80 servidores Red Hat Linux con distintas versiones de sistema operativo desde VMware on-premises hacia AWS.",architecture:"La ruta principal utilizó AWS MGN para replicar directamente a EC2 los servidores soportados. Para versiones de sistema operativo no compatibles con MGN fue necesario un flujo alternativo basado en imágenes.",contribution:"Participé en el trabajo de infraestructura y migración, incluyendo el camino alternativo: crear una imagen desde el workload VMware on-premises, subirla a S3, crear una AMI y lanzar la instancia EC2 resultante.",outcome:"Una estrategia mixta que permitió migrar a EC2 tanto workloads Red Hat soportados por MGN como aquellos no compatibles.",services:["AWS MGN","EC2","S3","AMI","VMware","Red Hat Linux"],diagram:["VMware","MGN","EC2","Fallback: Imagen → S3","AMI → EC2"]},
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",category:"CI/CD & Migración",title:"Migración de Plataforma de Pagos para Transporte",challenge:"Dar soporte a un programa grande de migración de una aplicación de pagos para transporte en Estados Unidos.",architecture:"Mi alcance estuvo principalmente en la capa de pipelines y delivery, más que en la plataforma AWS propiamente dicha.",contribution:"Reorganicé y adapté pipelines basados en GitHub para alinear el proceso de deployment de la aplicación con el entorno objetivo de la migración.",outcome:"Workflows de deployment mejor alineados con el destino de migración y el proceso de entrega.",services:["GitHub","GitHub Actions","CI/CD","Migration"],diagram:["Código","GitHub","Pipelines","Plataforma Objetivo"]},
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",category:"Migración AWS",title:"Migración MGN con Arquitectura Auto Scaling",challenge:"Migrar workloads hacia AWS preparando al mismo tiempo una arquitectura objetivo escalable y una base estructurada de cuentas.",architecture:"El entorno objetivo combinó AWS MGN, EC2, Auto Scaling y Load Balancers, junto con AWS Control Tower y Organizations para la estructura general de AWS.",contribution:"Trabajé sobre los componentes de migración e infraestructura y también sobre pipelines basados en GitHub utilizados en el proceso de delivery.",outcome:"Una ruta de migración respaldada por una arquitectura EC2 más escalable y una base de cuentas AWS estructurada.",services:["AWS MGN","EC2","Auto Scaling","Load Balancers","Control Tower","Organizations","GitHub"],diagram:["On-Prem","AWS MGN","EC2 Auto Scaling","Load Balancer","Aplicación"]},
      {company:"Caylent",logo:"https://caylent.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=caylent.com&sz=128",initials:"C",category:"Migración Windows & SQL",title:"Migración de Windows IIS y SQL Server a AWS",challenge:"Migrar servidores Windows de aplicación ejecutando IIS y workloads SQL Server hacia AWS.",architecture:"El objetivo actual se basa en servidores Windows sobre EC2 ejecutando IIS y SQL Server también sobre EC2, con Grafana utilizado para monitoreo y alarmas.",contribution:"Estoy trabajando sobre la infraestructura AWS, el contexto de migración Windows/IIS y SQL, monitoreo con Grafana y pipelines en GitHub.",outcome:"Una arquitectura objetivo basada en EC2 para aplicación y base de datos con visibilidad operativa mediante monitoreo y alertas.",services:["EC2","Windows Server","IIS","SQL Server","Grafana","GitHub","CI/CD"],diagram:["Usuarios","Load Balancer","EC2 / IIS","EC2 / SQL Server","Grafana"]}
    ],
    certifications:[
      {category:"AWS",name:"Well-Architected Proficient",badge:"AWS",logo:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=thumbnail",logoFallback:"https://aws.amazon.com/favicon.ico"},
      {category:"AWS",name:"AWS API Security",badge:"AWS",logo:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=thumbnail",logoFallback:"https://aws.amazon.com/favicon.ico"},
      {category:"AI",name:"Claude Certified Associate — Foundations",badge:"AI",logo:"https://claude.ai/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=claude.ai&sz=128"},
      {category:"Agile",name:"Scrum Foundation Professional Certificate (SFPC) — Spanish",badge:"S",logo:"https://certiprof.com/favicon.ico",logoFallback:"https://www.google.com/s2/favicons?domain=certiprof.com&sz=128"},
      {category:"AWS",name:"AWS Partner: Cloud Economics Accreditation",badge:"AWS",logo:"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1280px-Amazon_Web_Services_Logo.svg.png?utm_source=es.wikipedia.org&utm_campaign=index&utm_content=thumbnail",logoFallback:"https://aws.amazon.com/favicon.ico"}
    ],
    education:[
      {institution:"Instituto Superior Tecnologico Empresarial Argentino (ISTEA)",program:"Educación superior — Information Technology",period:"2020 — 2024"},
      {institution:"Ingeniero Eduardo Latzina",program:"Secundario — Técnico en Computación",period:"2006 — 2013"}
    ],
    skills:[
      {title:"Infraestructura & Arquitectura AWS",level:"Foco principal",items:["AWS","EC2","ECS","Lambda","S3","IAM","Route 53","API Gateway","Load Balancers","Control Tower","Organizations","IAM Identity Center"]},
      {title:"Migraciones Cloud",level:"Foco principal",items:["AWS MGN","VMware a AWS","Workloads Windows","Linux / Red Hat","Importación AMI","Planificación de Cutover"]},
      {title:"Infrastructure as Code & Delivery",level:"Foco principal",items:["Terraform","Terragrunt","AWS CDK","GitHub Actions","Azure DevOps","CI/CD","Git"]},
      {title:"Operaciones & Observabilidad",level:"Foco principal",items:["Grafana","Datadog","Splunk","ServiceNow","Python","Boto3","Linux"]},
      {title:"Contenedores",level:"Complementario",items:["Docker","ECS","ECR","Kubernetes","Helm","EKS"]},
      {title:"Base de Infraestructura",level:"Experiencia previa",items:["Windows Server","Active Directory","DNS","DHCP","IIS","Exchange","SharePoint","SQL Server","Office 365"]}
    ]
  }
};