const translations={
en:{
"nav.about":"About","nav.journey":"Journey","nav.cases":"Case studies","nav.certifications":"Certifications","nav.skills":"Skills","nav.education":"Education","nav.contact":"Contact",
"hero.eyebrow":"AWS • Cloud Architecture • Migrations","hero.greeting":"Hi, I'm","hero.lead":"Senior Cloud Engineer focused on AWS infrastructure, cloud migrations, Infrastructure as Code and the operational side of architecture.","hero.cases":"Explore case studies","hero.focus":"Focus","hero.location":"Based in","hero.architectureLabel":"Career evolution","hero.architectureTitle":"From on-prem infrastructure to AWS migrations and cloud architecture.","hero.path1":"Support","hero.path2":"Infrastructure","hero.path3":"Cloud & DevOps","hero.path4":"Senior Cloud","hero.architectureFooter":"continuous growth",
"about.kicker":"About","about.title":"Infrastructure experience built from the ground up.","about.p1":"My career started with hands-on technical support and physical Windows infrastructure, then evolved through enterprise platforms, DevOps and finally AWS cloud engineering.","about.p2":"Today I focus mainly on AWS infrastructure and migrations. I like understanding the full path of a workload — networking, compute, identity, automation, deployment and operations — and making the architecture understandable for the teams that will run it.","about.ownershipTitle":"Responsibility","about.ownershipText":"Take ownership of the task, understand the impact and move it forward professionally.","about.calmTitle":"Calm under pressure","about.calmText":"Troubleshoot methodically and keep communication clear when systems or timelines are under pressure.","about.teamTitle":"Teamwork","about.teamText":"Share context, help teammates and work across technical and geographic boundaries.",
"journey.kicker":"Career journey","journey.title":"What each stage added.","journey.intro":"A timeline of the technical foundation, cloud transition and professional lessons behind my current role.","cases.kicker":"Selected case studies","cases.title":"Migration and infrastructure work.","cases.intro":"The client names and sensitive details are intentionally omitted. Each case focuses on the problem, architecture and my contribution.","certs.kicker":"Certifications","certs.title":"Continuous learning.","certs.intro":"Certifications and accreditations currently listed on my professional profile.","skills.kicker":"Skills","skills.title":"Primary focus first.","skills.intro":"Technologies grouped by how they fit into my work today and the foundation I built earlier in my career.","education.kicker":"Education","education.title":"Technical foundations.","contact.kicker":"Contact","contact.title":"Let's talk cloud, infrastructure and migrations.","contact.text":"LinkedIn is the easiest way to reach me.","dyn.technical":"Technical growth","dyn.values":"Professional growth","dyn.challenge":"Challenge","dyn.architecture":"Architecture","dyn.contribution":"My contribution","dyn.outcome":"Outcome"},
es:{
"nav.about":"Sobre mí","nav.journey":"Trayectoria","nav.cases":"Casos de estudio","nav.certifications":"Certificaciones","nav.skills":"Skills","nav.education":"Educación","nav.contact":"Contacto",
"hero.eyebrow":"AWS • Arquitectura Cloud • Migraciones","hero.greeting":"Hola, soy","hero.lead":"Senior Cloud Engineer enfocado en infraestructura AWS, migraciones cloud, Infrastructure as Code y el lado operativo de la arquitectura.","hero.cases":"Ver casos de estudio","hero.focus":"Foco","hero.location":"Ubicación","hero.architectureLabel":"Evolución profesional","hero.architectureTitle":"De infraestructura on-prem a migraciones AWS y arquitectura cloud.","hero.path1":"Soporte","hero.path2":"Infraestructura","hero.path3":"Cloud & DevOps","hero.path4":"Senior Cloud","hero.architectureFooter":"crecimiento continuo",
"about.kicker":"Sobre mí","about.title":"Experiencia en infraestructura construida desde la base.","about.p1":"Mi carrera comenzó con soporte técnico hands-on e infraestructura física Windows, y luego evolucionó por plataformas enterprise, DevOps y finalmente cloud engineering en AWS.","about.p2":"Hoy me enfoco principalmente en infraestructura AWS y migraciones. Me gusta entender el recorrido completo de un workload — networking, compute, identidad, automatización, deployment y operación — y hacer que la arquitectura sea entendible para los equipos que la van a operar.","about.ownershipTitle":"Responsabilidad","about.ownershipText":"Tomar ownership de la tarea, entender su impacto y llevarla adelante de forma profesional.","about.calmTitle":"Calma bajo presión","about.calmText":"Hacer troubleshooting de forma metódica y mantener una comunicación clara cuando los sistemas o los tiempos están bajo presión.","about.teamTitle":"Trabajo en equipo","about.teamText":"Compartir contexto, ayudar a compañeros y trabajar atravesando límites técnicos y geográficos.",
"journey.kicker":"Trayectoria profesional","journey.title":"Qué aportó cada etapa.","journey.intro":"Una línea de tiempo de la base técnica, la transición a cloud y los aprendizajes profesionales detrás de mi rol actual.","cases.kicker":"Casos de estudio seleccionados","cases.title":"Trabajo de migración e infraestructura.","cases.intro":"Los nombres de clientes y detalles sensibles se omiten intencionalmente. Cada caso se enfoca en el problema, la arquitectura y mi contribución.","certs.kicker":"Certificaciones","certs.title":"Aprendizaje continuo.","certs.intro":"Certificaciones y acreditaciones que actualmente figuran en mi perfil profesional.","skills.kicker":"Skills","skills.title":"Primero, el foco principal.","skills.intro":"Tecnologías agrupadas según cómo encajan en mi trabajo actual y la base que construí al principio de mi carrera.","education.kicker":"Educación","education.title":"Bases técnicas.","contact.kicker":"Contacto","contact.title":"Hablemos de cloud, infraestructura y migraciones.","contact.text":"LinkedIn es la forma más simple de contactarme.","dyn.technical":"Crecimiento técnico","dyn.values":"Crecimiento profesional","dyn.challenge":"Desafío","dyn.architecture":"Arquitectura","dyn.contribution":"Mi contribución","dyn.outcome":"Resultado"}};

const root=document.documentElement;let currentLanguage=localStorage.getItem("language")||"en";
function t(k){return translations[currentLanguage][k]||k}
function applyLanguage(lang){currentLanguage=lang;root.lang=lang;document.getElementById("languageToggle").textContent=lang==="en"?"ES":"EN";document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});localStorage.setItem("language",lang);renderDynamicContent()}
function renderCareer(){document.getElementById("careerTimeline").innerHTML=portfolioContent[currentLanguage].career.map((job,i)=>`<article class="career-card reveal visible"><div class="career-rail"><span class="career-dot"></span><span class="career-line"></span></div><div class="career-main"><div class="career-head"><div>
  <div class="company-title-row">
    <span class="brand-logo-shell">
      <img class="company-logo" src="${job.logo}" alt="${job.company} logo"
           onerror="if(this.dataset.fallback!=='1'){this.dataset.fallback='1';this.src='${job.logoFallback}'}else{this.style.display='none';this.nextElementSibling.style.display='grid'}">
      <span class="brand-logo-fallback">${job.initials || job.company.slice(0,2)}</span>
    </span>
    <h3>${job.company}</h3>
  </div>
  ${job.location?`<p class="career-location">${job.location}</p>`:""}
</div><span class="career-index">${String(i+1).padStart(2,"0")}</span></div><div class="career-roles">${job.roles.map(r=>`<div class="career-role-row"><strong>${r.role}</strong><span>${r.period}</span></div>`).join("")}</div><p class="career-summary">${job.summary}</p><div class="learning-grid"><div class="learning-card"><h4>${t("dyn.technical")}</h4><ul>${job.technical.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="learning-card"><h4>${t("dyn.values")}</h4><ul>${job.professional.map(x=>`<li>${x}</li>`).join("")}</ul></div></div></div></article>`).join("")}
function renderDiagram(nodes){return `<div class="mini-diagram">${nodes.map((n,i)=>`<div class="diagram-node">${n}</div>${i<nodes.length-1?`<span class="diagram-arrow">→</span>`:""}`).join("")}</div>`}
function renderCases(){document.getElementById("caseStudies").innerHTML=portfolioContent[currentLanguage].cases.map(item=>`<article class="case-card ${item.featured?"case-featured":""} reveal visible"><div class="case-top"><div><span class="case-company">${item.company}</span><span class="case-category">${item.category}</span></div><span class="case-arrow">↗</span></div><h3>${item.title}</h3><div class="case-details"><div><span>${t("dyn.challenge")}</span><p>${item.challenge}</p></div><div><span>${t("dyn.architecture")}</span><p>${item.architecture}</p></div><div><span>${t("dyn.contribution")}</span><p>${item.contribution}</p></div><div><span>${t("dyn.outcome")}</span><p>${item.outcome}</p></div></div><div class="case-architecture">${renderDiagram(item.diagram)}</div><div class="tag-list">${item.services.map(x=>`<span>${x}</span>`).join("")}</div></article>`).join("")}
function renderCertifications(){document.getElementById("certificationGrid").innerHTML=portfolioContent[currentLanguage].certifications.map(i=>`<article class="cert-card reveal visible"><div class="cert-logo-shell"><img class="cert-logo" src="${i.logo}" alt="${i.category} logo" onerror="if(this.dataset.fallback!=='1'){this.dataset.fallback='1';this.src='${i.logoFallback}'}else{this.style.display='none';this.nextElementSibling.style.display='grid'}"><span class="cert-logo-fallback">${i.badge}</span></div><div><span class="cert-issuer">${i.category}</span><h3>${i.name}</h3></div></article>`).join("")}
function renderEducation(){document.getElementById("educationGrid").innerHTML=portfolioContent[currentLanguage].education.map(i=>`<article class="education-card reveal visible"><span class="education-period">${i.period}</span><h3>${i.institution}</h3><p>${i.program}</p></article>`).join("")}
function renderSkills(){document.getElementById("skillsGrid").innerHTML=portfolioContent[currentLanguage].skills.map(g=>`<article class="skill-card reveal visible"><span class="skill-level">${g.level}</span><h3>${g.title}</h3><div class="tag-list">${g.items.map(x=>`<span>${x}</span>`).join("")}</div></article>`).join("")}
function renderDynamicContent(){renderCareer();renderCases();renderCertifications();renderEducation();renderSkills()}
const savedTheme=localStorage.getItem("theme"),systemLight=window.matchMedia("(prefers-color-scheme: light)").matches;root.dataset.theme=savedTheme||(systemLight?"light":"dark");
document.getElementById("themeToggle").addEventListener("click",()=>{const n=root.dataset.theme==="dark"?"light":"dark";root.dataset.theme=n;localStorage.setItem("theme",n)});
document.getElementById("languageToggle").addEventListener("click",()=>applyLanguage(currentLanguage==="en"?"es":"en"));
const mobileNav=document.getElementById("mobileNav"),menuButton=document.getElementById("menuButton");menuButton.addEventListener("click",()=>mobileNav.classList.toggle("open"));mobileNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mobileNav.classList.remove("open")));
window.addEventListener("scroll",()=>document.getElementById("siteHeader").classList.toggle("scrolled",window.scrollY>8));document.getElementById("year").textContent=new Date().getFullYear();applyLanguage(currentLanguage);
